name: daily_journal
description: A daily journal application built with Flutter.

# Prevent accidental publication to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Application version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.3
  provider: ^6.0.5

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/images/grav_journal.png
    - assets/images/logo.png

  # Uncomment and customize fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
